### ISSUE TITLE
Round Robin Algorithm Generates Wrong Output

### ISSUE THREAD

**Issue by aa22dev** [boonsuen/process-scheduling-solver#5]
The output generated by the algorithm is wrong as checked for the following input:
| AT 	| BT 	|
|---	|---	|
| 22 	| 18 	|
| 4  	| 6 	|
| 16 	| 10 	|
| 2 	| 32 	|
| 10 	| 17 	|

Time quantum = 10

The output generated is:
![image](https://user-images.githubusercontent.com/25408054/208287333-a900c01d-6fb0-4b7e-a44f-16066ab7f4d1.png)

However, the expected output is:
![image](https://user-images.githubusercontent.com/25408054/208287384-5e0e1dfc-4d78-40e4-becb-09112b8d6df7.png)

**Comment by boonsuen** [comment]
The original output generated should be correct, please double check.

**Comment by aa22dev** [comment]
> The original output generated should be correct, please double check.

I have double-checked, and the output generated is wrong. 
I have manually tested it also.
The reason is this Gantt chart,
![image](https://user-images.githubusercontent.com/25408054/208303063-6073765a-b05c-49fe-a7a1-c9d4ab2a507e.png)
In this Gantt chart generated, the job D, B, E, D are executed whereas job D, B, E, C, A must be executed before going to job D again

So, the correct Gantt chart should be
![image](https://user-images.githubusercontent.com/25408054/208303354-cfc51799-8c6d-41fa-a3f2-c3e3e1229e28.png)
Making the correct output table.

**Comment by boonsuen** [comment]
At the time of 12, B and E arrived and after that D will have to **re-queue** to the back (B, E, D). At this point C has not arrived yet. That is why the gantt chart starts with D, B, E, D...

**Comment by aa22dev** [comment]
> At the time of 12, B and E arrived and after that D will have to **re-queue** to the back (B, E, D). At this point C has not arrived yet. That is why the Gantt chart starts with D, B, E, D...

At the time of 12, B and E arrived, So, B is executed and E is executed but after the execution of E, the time is 28 which means all the processes after B and E have arrived so, C and A must be executed before D.

**Comment by boonsuen** [comment]
D will be executed first based on the ready queue as I've mentioned above. Follow the sequence of the queue.

**Comment by aa22dev** [comment]
> D will be executed first based on the ready queue as I've mentioned above. Follow the sequence of the queue.

Shouldn't ready queue be updated to add proccess which have arrived at time interval of 28 as that is how it should work. Right?

Round Robin Algorithm executes all the proccesses based on their time of arrival and time quantum and in this case all the proccesses arrived before time interval of 28 in first cycle, so they must be executed before starting another cycle.
